version: "3"

tasks:
  up:
    desc: Build and start containers in detached mode
    cmd: docker compose up -d --build

  down:
    desc: Stop and remove containers
    cmd: docker compose down

  stop:
    desc: Stop containers without removing them
    cmd: docker compose stop

  logs:
    desc: Follow the app container logs
    cmd: docker compose logs -f app

  restart:
    desc: Restart the app container
    cmd: docker compose restart app

  install:
    desc: Reinstall dependencies from lock file (use after pulling dependency updates)
    cmd: docker compose exec app npm ci

  build:
    desc: Build for production
    cmd: docker compose exec app npx vite build

  test:
    desc: Run tests
    cmd: docker compose exec app npx vitest run

  test-watch:
    desc: Run tests in watch mode
    cmd: docker compose exec app npx vitest

  test-file:
    desc: "Run a specific test file (usage: task test-file -- src/path/to/file.test.tsx)"
    cmd: docker compose exec app npx vitest run {{.CLI_ARGS}}

  add:
    desc: "Add a package (usage: task add -- <package>)"
    cmd: docker compose exec app npm install {{.CLI_ARGS}}

  remove:
    desc: "Remove a package (usage: task remove -- <package>)"
    cmd: docker compose exec app npm uninstall {{.CLI_ARGS}}
